### ISSUE TITLE
Submission 1 Review

### ISSUE THREAD

**Issue by SWHarrison** [galkochris/CS13#1]
Decode: Does not work due to this line: 
```convert = convert + int(i)*int(base**(len(digits) - digits.index(i) - 1))```

Specifically, the digits.index(i) will not work when there are repeated digits since it will always grab the index of the first number. For example, '1101' in base 2 becomes 24, since it adds 8 for each 1 since that's the value that should be used for the first 1, but not the subsequent 1's.

Encode: Does not work. I encourage you to reach out and find time to go over encoding with me.

Binary Search: Works as expected, nice work!

**Comment by galkochris** [comment]
Thank you for the feedback, I was able to sit down with my roommate, Ben, who walked me through where I went wrong and helped me come up with a simplified version of what I was doing, that also fixed the errors I was encountering with improper decoding and encoding. Thank you!
