### ISSUE TITLE
Feedback on linked lists, stacks, and queues

### ISSUE THREAD

**Issue by Anisha7** [galkochris/CS13#2]
Great work!

**Linked List**
Good job on successfully completing all of the challenges. Challenge yourself further by implementing a doubly linked lists and adding new tests for it.

**Stacks**
Good job on successfully completing your LinkedStack. Looks like your ArrayStack does not pass unit tests. One error I see is in your peek method. Why are you returning `self.peek & self.list.pop(self.length - 1)`? self.peek is a method and the other is pop, and `&` is not a python symbol. Think about what you are really trying to return here. 

Another quick tip: .pop() on lists without a given index removes the last item in the list by default. 

**Queues**
Good job on successfully completing all of the challenges. Challenge yourself further by implementing a circular buffer to improve runtime and writing new unit tests.

**Comment by galkochris** [comment]
Thank you for the feedback! I was able to speak with another TA earlier, and resolved the issues.
