### ISSUE TITLE
Feedback on hash tables

### ISSUE THREAD

**Issue by Anisha7** [galkochris/CS13#3]
Great work on your hash table. Further challenge yourself by implementing an alternative hash collision strategy (linear probing, etc) and write new unit tests to check robustness.

For full credit on your technical article, add 2 images /diagrams relevant to topic or a working code sample. 

For full credit on article feedback, you need to make sure the feedback is actionable.

**Comment by galkochris** [comment]
Thank you! my completed article has everything necessary to pass both the published and draft submission, and I hope those improvements can satisfy the requirements missed in the draft submission. Also I reviewed an additional article so that should suffice for improving the feedback given.
