### ISSUE TITLE
Feedback on trees

### ISSUE THREAD

**Issue by Anisha7** [galkochris/CS13#4]
Great attempt on your binary tree implementation. There are some errors in your find_node_recursive method. Make sure when you recursively call this method, you are passing a node, not data, as the node parameter. Make sure all of your unit tests pass using both recursive and iterative find node methods!

**Comment by galkochris** [comment]
Thank you for the advice! I I remember changing some things around after submission for my delete method attempt, but commented them out until I can get it working. Until that time the standard methods all pass now.
