### ISSUE TITLE
CS 1.3 Submissions 6 and 7 Review

### ISSUE THREAD

**Issue by SWHarrison** [galkochris/CS13#5]
Sets: Does not work due to underlying issues with binary search tree. 8/9 of your tests fail.

Word Jumble: Works as expected, and very quickly!

```print('Impossible, perhaps The Archives are incomplete!')```
You are strong and wise, and I am very proud of you.

**Comment by galkochris** [comment]
Awesome Thank you! I switched over to a HashSet setup, which passes all my pre-built tests, and hopefully can sit down with you at another time to look at where exactly I can improve to get the TreeSet working.
